### ISSUE TITLE
styles dont load when not login

### ISSUE THREAD

**Issue by nicogaldo** [SimonPadbury/b4st#69]
Hi, as the title says, the styles are not seen inside the head when the session is not started. If I enter as an administrator it looks perfect, but when it does not, everything is broken, without styles.

**Comment by peterbradica** [comment]
This has happened to me too. Has something changed in the latest build?

**Comment by peterbradica** [comment]
After I tried everything else (purge caches, turn off all plugins, reset htaccess etc) my last resort was to roll back this theme from V2.7 to V2.5 and the problem was fixed. 

Somehow the V2.7 doesn't load the header styles in the front end when you are not logged in.

**Comment by SimonPadbury** [comment]
Fixed, v2.7.1 — it should work now.

**Comment by MistaNeilo** [comment]
This isnt fixed for me - the enqueue still not working when logged out - i updated the cleanup.php file but still not resolved - any further changes coming for this?

**Comment by MistaNeilo** [comment]
If had to comment out following lines to make work

`// add_filter( 'script_loader_src', 'b4st_remove_script_version', 15, 1 );
// add_filter( 'style_loader_src', 'b4st_remove_script_version', 15, 1 );`

**Comment by SimonPadbury** [comment]
OK. I have commented out that *remove_script_version* stuff.

I was trying to implement a suggestion in [issue #68](https://github.com/SimonPadbury/b4st/issues/68) but it was written in shorthand PHP and I messed up in trying to write it out fully. If there's anyone who can fix that, please go ahead.

But it's just for tidying up the `<head>` somewhat — you don't really need it.
